/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.obstaclesupport;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Obstaclesupport extends AbstractObstaclesupport { 
	public Obstaclesupport(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
