/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.roversupport;


import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.rover.SingletonConfigurations;

public class Roversupport extends AbstractRoversupport { 
	
	private SingletonConfigurations configurations;
	private int da;
	
	
	public Roversupport(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		try {
			this.configurations = SingletonConfigurations.getInstance();
			System.out.println("[Support] all conf setted");
		} catch(Exception e) {
			e.printStackTrace();
		}
		
	}
	
	public void setDa(int da) {
		this.da = da;
	}
	
	public boolean goalTest(int currentPosition) {
		int difference = da-currentPosition;
		if ( Math.abs(difference) <= configurations.getFinalPointTollerance()  ) 
			return true;
		else 
			return false;
	}
}
