/* Generated by AN DISI Unibo */ 
package it.unibo.rover;

import java.util.Date;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Rover extends AbstractRover {

	private int da;
	private int attemptRight;
	private long startTimeForward;
	private int duration;
	
	public Rover(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
		this.attemptRight = 0;
	}
	
	public void createRobotUnity() {
		createSimulatedActor("Prefabs/CustomActor", (float)-33.7, 0, 20, 0, 0, 0, 0);
	}
	
	public int getAttemptRightTotalTime(int searchTimeForward) {
		return this.attemptRight*searchTimeForward;
	}

	public void setAttemptRight(int attemptRight) {
		this.attemptRight = attemptRight;
	}
	
	public void incAttemptRight() {
		this.attemptRight++;
		System.out.println("[ROVER] attempt right: " + this.attemptRight);
	}

	public void decAttemptRight() {
		if(this.attemptRight>0) this.attemptRight--;
		System.out.println("[ROVER] attempt right: " + this.attemptRight);
	}
	
	public void setDa(int da) {
		this.da = da;
	}
	
	public int chooseDirection(int currentPoint, int finalPointTollerance) {
		System.out.println("[ROVER] Choosing direction: CP="+currentPoint+", FPT="+finalPointTollerance);
		int difference = da-currentPoint;
		if ( Math.abs(difference) <= finalPointTollerance  ) 
			return 0;									//stay there
		else if (difference > 0)		
			return 1;									//go DX
		else // (difference < 0)	
			return 2;									//go SX
	}
	
	public void exit() {
		System.exit(1);
	}
	
	public void saveStart() {
		this.startTimeForward = new Date().getTime();
	}
	
	public int getDurationTime() {
		long endTimeForward = new Date().getTime();
		int durationTimeForward = (int) (endTimeForward - this.startTimeForward);
		System.out.println("[ROVER] DurationTimeForward = "+durationTimeForward);
		return durationTimeForward;
	}
	
	public void saveStartGoHome(int duration) {
		this.startTimeForward = new Date().getTime();
		this.duration = duration;
	}
	
	public int getRemainingTime() {
		long endTimeForward = new Date().getTime();
		int durationTimeForward = (int) (endTimeForward - this.startTimeForward);
		System.out.println("[ROVER] DurationTimeForward = "+durationTimeForward);
		int durationTimeRemaining = (int) (this.duration - durationTimeForward);
		System.out.println("[ROVER] DurationTimeRemaining = "+durationTimeRemaining);
		return durationTimeRemaining;
	}
	
}
