/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.sonarsupport;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Sonarsupport extends AbstractSonarsupport { 
	
	public Sonarsupport(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);		
	}
	
	public int goalTest(int da, int currentPoint, int finalPointTollerance) {
		int difference = da-currentPoint;
		if ( Math.abs(difference) <= finalPointTollerance  ) 
			return 0;//stay there
		else if (difference > 0)		
			return 1;//go DX
		else//(difference < 0)	
			return 2;//go SX
	}
}
