/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.sonar2;
import java.io.BufferedReader;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Sonar2 extends AbstractSonar2 {
	
	private BufferedReader sonarReader;
	
	public Sonar2(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void startSonarProcess() {
  		try {
			Process p = Runtime.getRuntime().exec("sudo ./SonarAlone");
			sonarReader = new BufferedReader(new java.io.InputStreamReader(p.getInputStream()));
		} catch(Exception e) {
 			e.printStackTrace();
		}		
	}
	
	public int getDistanceFromSonar(){
		try {
			String distance = sonarReader.readLine();			
			println("[ Sonar2] getDistanceFromSonar " + distance  ); 
			return Integer.parseInt(distance);
		} catch(Exception e) {
 			e.printStackTrace();
 			return 0; 
		}
	}
}
