/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.usercmdsupport;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Usercmdsupport extends AbstractUsercmdsupport { 
	public Usercmdsupport(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
