/* Generated by AN DISI Unibo */ 
package it.unibo.rover;
import java.io.BufferedReader;
import java.io.FileReader;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Rover extends AbstractRover { 
	private int rotationTime;
	
	public Rover(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
		BufferedReader br = new BufferedReader(new FileReader("rotationTime.txt"));
		this.rotationTime = Integer.parseInt(br.readLine());
		br.close();
	}
	
	public void createRobotUnity() {
		createSimulatedActor("Prefabs/CustomActor", (float)-33.7, 0, 10, 0, 0, 0, 0);
	}
	
	public int getRotationTime() {
		return rotationTime;
	}
	
	public int multiply(int x, int y) {
		return x*y;
	}
	
}
